/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.gui;

/**
 *
 * @author USER
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    //Creamos materiales en el inventario con stock inicial
    private proyecto.modelo.Material pla = new proyecto.modelo.Material("PLA (Filamento 3D)", 0.05, 2000.0); //2000 gramos
    private proyecto.modelo.Material aluminio = new proyecto.modelo.Material("Aluminio (Bloque)", 0.35, 500.0); //500 cm3  
    //Instanciamos el gestor de archivos para guardar el historial
    private proyecto.Archivos.GestorArchivos gestor = new proyecto.Archivos.GestorArchivos();
    //Variables de control para las órdenes
    private proyecto.modelo.OrdenDeTrabajo ordenActual = null; // Guardará la última orden calculada
    private int contadorOrdenes = 1;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();     
        //Cambiar el título de la ventana
        this.setTitle("Sistema Gestión de Manufactura - Mecatrónica");
        //Cambiar el color de fondo de la ventana (Usa colores RGB)
        // Elige un gris muy claro o el color que prefieras
        this.getContentPane().setBackground(new java.awt.Color(240, 244, 248));
        // Llenar las opciones de la interfaz gráfica
        comboMaquina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Impresora 3D - Creality Ender", "Cortadora CNC - Router Pro" }));
        comboMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLA (Filamento 3D)", "Aluminio (Bloque)" }));
        txtPantalla.setText("Bienvenido al Sistema de Manufactura.\nSeleccione las opciones y presione 'Generar Cotización'.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPantalla = new javax.swing.JTextArea();
        btnGenerar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        comboMaterial = new javax.swing.JComboBox<>();
        comboMaquina = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        txtPantalla.setColumns(20);
        txtPantalla.setRows(5);
        jScrollPane1.setViewportView(txtPantalla);

        btnGenerar.setText("Generar Cotización");
        btnGenerar.addActionListener(this::btnGenerarActionPerformed);

        btnGuardar.setText("Guardar en Historial");

        jLabel4.setText("Resumen de la Orden:");

        jLabel3.setText("Cantidad a usar (g / cm2):");

        jLabel2.setText("Seleccione el Material:");

        jLabel1.setText("Seleccione la Máquina:");

        comboMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboMaquina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnGenerar)))
                        .addGap(220, 220, 220)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(comboMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnGuardar))
                .addGap(47, 47, 47)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        try {
            double cantidad = Double.parseDouble(txtCantidad.getText());
            if (cantidad <= 0) {
                txtPantalla.setText("Error: La cantidad de material debe ser un número mayor a cero.");
                return;
            }
            proyecto.modelo.Material materialSeleccionado = null;
            if (comboMaterial.getSelectedItem().toString().contains("PLA")) {
                materialSeleccionado = pla;
            } else {
                materialSeleccionado = aluminio;
            }
            proyecto.modelo.Maquina maquinaSeleccionada = null;
            String maqSeleccionada = comboMaquina.getSelectedItem().toString();
            if (maqSeleccionada.contains("Impresora 3D")) {
            //Creamos una instancia de Impresora3D usando la cantidad para estimar su volumen volumétrico
                maquinaSeleccionada = new proyecto.modelo.Impresora3D("IMP-01", "Creality", 150.0, 350.0, 210.0, cantidad * 0.5);
            } else {
            //Creamos una instancia de CortadoraCNC usando la cantidad para estimar el área de trabajo
                maquinaSeleccionada = new proyecto.modelo.CortadoraCNC("CNC-01", "Router Pro", 320.0, 1200.0, 15000, cantidad * 0.2);
             }
            materialSeleccionado.actualizarStock(cantidad);//Validamos el inventario
            //Creamos y calcular la Orden de Trabajo si el stock fue suficiente
        ordenActual = new proyecto.modelo.OrdenDeTrabajo(contadorOrdenes, maquinaSeleccionada, materialSeleccionado);
        ordenActual.calcularCostoTotal(cantidad);
        //Mostramos los resultados en el Text Area de la pantalla
        txtPantalla.setText("=== COTIZACIÓN GENERADA EXCELENTE ===\n" + 
                            ordenActual.generarResumen() + "\n\n" +
                            "Stock disponible restante de " + materialSeleccionado.getNombre() + ": " + materialSeleccionado.getCantidadDisponible() + "\n\n" +
                            "Presione el botón 'Guardar en Historial' para registrar esta orden en el archivo .txt.");
        } catch (NumberFormatException e) {
        //Atrapamos el error nativo si el usuario escribe letras en el campo de cantidad
            txtPantalla.setText("Error de Validación: Por favor, ingrese un valor numérico válido en el campo de cantidad.");
        }catch(proyecto.modelo.InventarioInsuficienteException e) {
            txtPantalla.setText(e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboMaquina;
    private javax.swing.JComboBox<String> comboMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtPantalla;
    // End of variables declaration//GEN-END:variables
}
